# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Repository\HourlyRateRepository:
        arguments:
            $redis: '@snc_redis.default'
    App\Repository\HourlyRateRepositoryInterface: '@App\Repository\HourlyRateRepository'

    App\Repository\CurrencyRepository:
        arguments:
            $redis: '@snc_redis.default'
    App\Repository\CurrencyRepositoryInterface: '@App\Repository\CurrencyRepository'

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client

    App\Service\RateProvider\BitpayRateProvider:
        autowire: true
        arguments:
            $apiUrl: 'https://bitpay.com/api/rates/{currency}'
            $currencyPlaceholder: '{currency}'

    App\Service\ApplicationCurrencyService:
        arguments:
            $supported:
                BTC: Bitcon
                ETH: Ethereum

    serializer.normalizer.datetime:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        arguments:
            $defaultContext:
                datetime_timezone: 'UTC'
                datetime_format: 'Y-m-d\TH:i:s\Z'
