nelmio_api_doc:
    documentation:
        info:
            title: Rate App
            description: Rate App
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^(?!(?:/api/doc)|(?:/$)){2,} # Accepts routes under / except /api/doc and "/" itself
